# Generated by Django 2.0.2 on 2019-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190421_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
